## Georges needs to add comments... 

##' Model implementing "Huisman, J., and Weissing, F.J. (2001).
##' Biological conditions for oscillations and chaos generated by multispecies
##' competition. Ecology 82, 2682–2695..
##'
##' Test case...
##' @title Huisman & Weissing 2001
##' @param d See paper
##' @param D See paper
##' @param S See paper
##' @author Georges Kunstler and Rich FitzJohn
##' @export
make_huisman_2001<- function(m=0.25, D=0.25, S=c(1, 1)) {
  defaults <- list(m=m, D=D, S=S)
  parameters <- make_parameters(defaults, environment())

  dydt <- function(t, ode.y, x, ...) {
    R <- ode.y[1:2]
    y <- ode.y[3:(2 +length(x))]
    gi <- g(x, R)
    dRdt <- D * (S - R) - colSums(y * gi * cbind(x, 1-x) )
    dydt <- y * (gi - m)
    c(dRdt, dydt)
  }
  dydt.deSolve <- function(...) {
    list(dydt(...))
  }

  ## Given traits 'x' and initial densities 'y', compute the
  ## equilibrium.  Return the equilibrium resource availability at the
  ## same time.
  equilibrium <- function(x, y, method="runsteady",
                          init_time=200,
                          max_time=1e5) {
    # Initial resources are set to 'S'
    y0 <- c(S, y)
    if (init_time > 0) {
      y0 <- unname(lsoda(y0, c(0, init_time), dydt.deSolve, x)[2,-1])
    }
    
    method <- match.arg(method, c("runsteady", "nleqslv", "simple"))
    if (method == "runsteady") {
      ans <- runsteady(y0, dydt.deSolve, x, times=c(0, Inf),
                       hmax=1)$y
    } else if (method == "nleqslv") {
      ans <- nleqslv(y0, function(y) dydt(0, y, x), global="none")$x
    } else if (method == "simple") {
      ans <- unname(lsoda(y0, c(init_time, max_time), dydt.deSolve, x)[2,-1])
    }

    list(R=ans[1:2], y=ans[3:(2+length(x))])
  }

  run <- function(x, y, times) {
    y0 <- c(S, y)
    res <- lsoda(y0, times, dydt.deSolve, x)
    list(t=res[,1],
         R=res[,2:3],
         y=res[,4:(3+length(x))])
  }

  g <- function(x, R) {
    pmin(R[1]/(   x    +  R[1]),
         R[2]/((1 - x) +  R[2]))
  }

 
  ret <- list(equilibrium  = equilibrium,
              run          = run,
              parameters   = parameters)
  class(ret) <- "model"
  ret
}
